combat_xp:
  ZOMBIE: 10.0
  SKELETON: 12.0
  CREEPER: 15.0
  SPIDER: 8.0
  CAVE_SPIDER: 10.0
  ENDERMAN: 25.0
  BLAZE: 20.0
  SLIME: 8.0
  MAGMA_CUBE: 10.0

  COW: 2.0
  PIG: 2.0
  CHICKEN: 1.0
  SHEEP: 2.0
  RABBIT: 1.0

  DEFAULT: 5.0
