combat_xp:
  ZOMBIE: 10.0
  SKELETON: 12.0
  CREEPER: 15.0
  SPIDER: 8.0
  CAVE_SPIDER: 10.0
  ENDERMAN: 25.0
  BLAZE: 20.0
  SLIME: 8.0
  MAGMA_CUBE: 10.0

  COW: 2.0
  PIG: 2.0
  CHICKEN: 1.0
  SHEEP: 2.0
  RABBIT: 1.0

  DEFAULT: 5.0

cooking_xp:
  COOKED_BEEF: 8.0
  COOKED_PORKCHOP: 8.0
  COOKED_MUTTON: 8.0
  COOKED_CHICKEN: 6.0
  COOKED_RABBIT: 6.0
  COOKED_COD: 7.0
  COOKED_SALMON: 9.0
  BAKED_POTATO: 5.0
  BREAD: 4.0
  COOKED_KELP: 3.0

  DEFAULT: 5.0

cooking:
  slot_timeout_minutes: 30
  cook_time_base: 600
  cook_time_reduction_per_level: 5
  burn_chance_base: 0.65
  burn_chance_decay: 0.045
